/* eslint-disable jsx-a11y/alt-text */
import { Metadata } from "next";
import Image from "next/image";

export interface GetPokemos {
  count: number;
  next: null;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}

export interface SinglePokemon {
  name: string;
  id: string;
}



export const metadata: Metadata = {
  title: "PokemonsPage",
  description: "Generated by create next app",
};

export default async function PokemonsPage() {



  const getPokemons = async (limit = 1, offset = 0) => {
    const data: GetPokemos = await fetch(`https://pokeapi.co/api/v2/pokemon?limit=${limit}&offset=${offset}`).then(res => res.json());

    const pokemons: Array<SinglePokemon> = data.results.map(pokemon => {
      const id = pokemon.url.split("/").at(-2)!;
      return ({ name: pokemon.name, id });
    })

    return pokemons

  }



  const list = await getPokemons(151);





  return (
    <div className="flex flex-col">
      <span>Pokemon  <small>List static</small></span>
      <div className="flex flex-wrap items-center justify-between">
        {list.map(pokemon =>
          <Image key={pokemon.id} src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/${pokemon.id}.svg`} alt={pokemon.name} width={100} height={100} />

        )}
      </div>

    </div>
  );
}