/* eslint-disable jsx-a11y/alt-text */
import { Metadata } from "next";
import { GetPokemos, SinglePokemon } from "./interfaces";
import { PokemonsGrid } from "./components";
import { notFound } from "next/navigation";



export const metadata: Metadata = {
  title: "PokemonsPage",
  description: "Generated by create next app",
};

export default async function PokemonsPage() {



  const getPokemons = async (limit = 1, offset = 0) => {
    const data: GetPokemos = await fetch(`https://pokeapi.co/api/v2/pokemon?limit=${limit}&offset=${offset}`).then(res => res.json());

    const pokemons: Array<SinglePokemon> = data.results.map(pokemon => {
      const id = pokemon.url.split("/").at(-2)!;
      return ({ name: pokemon.name, id });
    })
    // throw new Error("No se cargo nada");
    
    
    return pokemons

  }


  const list = await getPokemons(151);


  return (
    <div className="flex flex-col">
      <span className="text-7xl mb-3">Pokemon static<small className="text-5xl"> list</small></span>
      <PokemonsGrid list={list} />
    </div>
  );
}