import { Metadata } from "next";
import { PokemonsGrid } from "../pokemon/components";



export const metadata: Metadata = {
  title: "PokemonsFavoritePage",
  description: "Generated by create next app",
};

export default async function PokemonsPage() {


  return (
    <div className="flex flex-col">
      <span className="text-7xl mb-3">Pokemon <small className="text-5xl text-lime-500"> Favorites</small></span>
      <PokemonsGrid list={[]} />
    </div>
  );
}